name: Build and test crates (matrix)

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  crate-matrix:
    name: Run actions per crate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: ${{ fromJSON(inputs.matrix) }}
        check: ["test", "build", "build --release"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run action for crate
        shell: bash
        run: |
          echo "Running '${{ matrix.check }}' for crate '${{ matrix.crate }}'"
          cargo ${{ matrix.check }} -p "${{ matrix.crate }}"