name: Build workspace crates

on:
  workflow_call:
    inputs:
      crates:
        required: true
        default: "[]"
        type: string
        description: "JSON array of crate names to build (e.g. [\"crate1\", \"crate2\"])"
      actions:
        required: true
        default: "[]"
        type: string
        description: "JSON array of cargo actions to run for each crate (e.g. [\"test\", \"build --release\"])"

jobs:
  setup-builder:
    name: Setup Rust & Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.rust-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust & push cache
        id: rust-cache
        uses: ./.github/actions/rust-cache
        with:
          action: push

  run-builder:
    name: "${{ matrix.crate }}"
    needs: setup-builder
    strategy:
      fail-fast: false
      matrix:
        crate: ${{ fromJson(inputs.crates) }}
    uses: ./.github/workflows/sub/crates-builder-internal.yaml
    with:
      crate: ${{ matrix.crate }}
      actions: ${{ inputs.actions }}