name: Push Coverage Baseline

on:
  push:
    branches:
      - dev/trunk
      - main

jobs:
  upload-coverage:
    name: Tests & Coverage
    environment: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Rust & push cache
        uses: ./.github/actions/rust-cache
        with:
          action: push
          packages: '["cargo-tarpaulin"]'

      - name: Restore Rust cache
        uses: ./.github/actions/rust-cache
        with:
          action: pull
          packages: '["cargo-tarpaulin"]'

      - name: Run tests with coverage
        run: |
          cargo tarpaulin --workspace --exclude cargo-extract --out Lcov --output-dir ./coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
